<?xml version="1.0" encoding="utf-8"?><Database Name="VideoGameStuff" Class="VideoGamesDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=VideoGameStuff;Integrated Security=True" SettingsObjectName="VideoGames.Data.Properties.Settings" SettingsPropertyName="VideoGameStuffConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VideoGames" Member="VideoGames">
    <Type Name="VideoGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Developer" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>